# Generated by Django 4.2.4 on 2024-06-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='label')),
                ('label', models.CharField(max_length=64, verbose_name='label')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='name')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reserves', to='reserve.room', verbose_name='Room Number')),
            ],
            options={
                'verbose_name': 'Reserve',
                'verbose_name_plural': 'Reserves',
                'ordering': ['-id'],
            },
        ),
    ]
