# Generated by Django 4.2.4 on 2024-06-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='reservation_time_end',
            field=models.DateTimeField(null=True, verbose_name='reservation_time_end'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='reservation_time_start',
            field=models.DateTimeField(null=True, verbose_name='reservation_time_start'),
        ),
    ]
